export enum ActionTypes {
  ADD_PRODUCT_IN_CART_LIST = 'ADD_PRODUCT_IN_CART_LIST',
  UPDATE_PRODUCT_QUANTITY_IN_HOME_TO_CART_LIST = 'UPDATE_PRODUCT_QUANTITY_IN_HOME_TO_CART_LIST',
  UPDATE_PRODUCT_QUANTITY_IN_CART_LIST = 'UPDATE_PRODUCT_QUANTITY_IN_CART_LIST',
  REMOVE_PRODUCT_IN_CART_LIST = 'REMOVE_PRODUCT_IN_CART_LIST',
  RESET_CART_LIST = 'RESET_CART_LIST',
}
